import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { Header } from "@/components/features";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Dictionary",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer>
          <h2>Im a footer</h2>
        </footer>
      </body>
    </html>
  );
}
