import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import React from "react";
import { dbConnect } from "@/lib";
import { getServerSession } from "next-auth";
import { MainLayout, SessionLayout } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Dictionary",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  dbConnect();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionLayout session={session}>
          <MainLayout>{children}</MainLayout>
        </SessionLayout>
      </body>
    </html>
  );
}
